on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: apimysql01.azurecr.io
        username: ${{ secrets.acr_apimysql01_username }}
        password: ${{ secrets.acr_apimysql01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t apimysql01.azurecr.io/rolandndev:${{ github.sha }}
        docker push apimysql01.azurecr.io/rolandndev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_rolandndev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rolandndevfd9f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rolandndevfd9f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rolandndevfd9f
        container-registry-url: apimysql01.azurecr.io
        container-registry-username: ${{ secrets.acr_apimysql01_username }}
        container-registry-password: ${{ secrets.acr_apimysql01_password }}
        secret-name: rolandndevdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: rolandndevfd9f
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          apimysql01.azurecr.io/rolandndev:${{ github.sha }}
        imagepullsecrets: |
          rolandndevdockerauth